tisnik/most-popular-python-libs

jq.py/03_process_as_json.py

Fixed issue #9: D100: Missing docstring in public module

Fixed issue #9: D100: Missing docstring in public module

---

jq.py/03_process_as_json_to_text_B.py

Fixed issue #10: D100: Missing docstring in public module

Fixed issue #10: D100: Missing docstring in public module

---

jq.py/03_process_as_json_to_text.py

Fixed issue #11: D100: Missing docstring in public module

Fixed issue #11: D100: Missing docstring in public module

---

jq.py/04_no_error_handling.py

Fixed issue #12: D100: Missing docstring in public module

Fixed issue #12: D100: Missing docstring in public module

---

jq.py/05_error_handling.py

Fixed issue #13: D100: Missing docstring in public module

Fixed issue #13: D100: Missing docstring in public module

---

jq.py/06_first_value.py

Fixed issue #14: D100: Missing docstring in public module

Fixed issue #14: D100: Missing docstring in public module

---

pil/46_image_morph_dilate_8.py

Fixed issue #39

---

pil/46_image_morph_dilate_8.py

Fixed issue #38

---

pil/46_image_morph_dilate_8.py

Fixed issues #36 and #37

---

pil/41_image_morph_bitmap.py

Fixed issue #35

---

pil/42_image_morph_negate.py

Fixed issue #23

---

flask/01_basic_app/01_basic_app.py

Fixed issue #22

---

pil/28_circles.py

Fixed issue #24

---

pil/48_image_morph_erosion_8.py

Fixed issue #25

---

pil/48_image_morph_erosion_8.py

Fixed issue #26

---

pil/47_image_morph_erosion_4.py

Fixed issue #27

---

pil/47_image_morph_erosion_4.py

Fixed issue #28

---

pil/43_image_morph_edges.py

Fixed issue #29

---

pil/44_image_morph_inner_edges.py

Fixed issue #30

---

pil/45_image_morph_dilate_4.py

Fixed issue #31

---

pil/45_image_morph_dilate_4.py

Fixed issue #33

---

pil/45_image_morph_dilate_4.py

Fixed issue #34

---

jq.py/02_process_as_text.py

Added licence header into 02_process_as_text.py
Fixes #57

Added licence header into 02_process_as_text.py

---

jq.py/02_process_as_text_to_text.py

Added licence header into 02_process_as_text_to_text.py
Fixes #58

Added licence header into 02_process_as_text_to_text.py

---

jq.py/03_process_as_json.py

Add license header into jq.py/03_process_as_json.py
Fixes #59

Added licence header into 03_process_as_json.py

---

jq.py/04_no_error_handling.py

Add license header into jq.py/04_no_error_handling.py
Fixes #60

Added licence header into 04_no_error_handling.py

---

jq.py/05_error_handling.py

Add license header into jq.py/04_no_error_handling.py
Fixes #61

Added licence header into 05_error_handling.py

---

jq.py/03_process_as_json_to_text.py

Added license text into `jq.py/03_process_as_json_to_text.py`
Fixes #64

Added license text into `jq.py/03_process_as_json_to_text.py`

---

jq.py/03_process_as_json_to_text_B.py

Added license text into `jq.py/03_process_as_json_to_text_B.py`
Fixes #63

Added license text into `jq.py/03_process_as_json_to_text_B.py`

---

jq.py/06_first_value.py

Add license header into `jq.py/06_first_value.py`
Fixes #62

Add license header into `jq.py/06_first_value.py`

---

jq.py/06_first_value_type.py

Add license header into `jq.py/06_first_value_type.py`
Fixes #65

Add license header into `jq.py/06_first_value_type.py`

---

jq.py/07_non_existing_key_type.py

Added license header (issue #67)

---

jq.py/07_non_existing_key_type.py
jq.py/08_escape_characters.py

Fix issue 68

---

jq.py/07_non_existing_key_type.py
jq.py/09_get_license.py

Fix issue 69

---

jq.py/07_non_existing_key_type.py
jq.py/10_summary_for_all_endpoints_get.py

Fix issue 70

---

jq.py/07_non_existing_key_type.py
jq.py/11_summary_for_all_endpoints_delete.py

Fix issue 71

---

jq.py/07_non_existing_key_type.py
jq.py/12_search_endpoint.py

Fix issue 72

---

jq.py/07_non_existing_key_type.py
jq.py/13_has_get_method.py

Fix issue 73

---

jq.py/07_non_existing_key_type.py
jq.py/14_has_delete_method.py

Fix issue 74

---

jq.py/07_non_existing_key_type.py
jq.py/15_get_parameters.py

Fix issue 75

---

pyjq/05_non_existing_key.py

Added license header (issue #80)

---

pyjq/02_process_as_json.py

Added license header (issue #77)

---

pyjq/03_first_value.py

Added license header (issue #78)

---

pyjq/04_non_existing_key.py

Added license header (issue #79)

---

pyjq/01_basic_installation_check.py

Added license header (issue #76)

---

pyjq/06_escape_characters.py

Added license header (issue #81)

---

pyjq/07_get_license.py

Added license header (issue #82)

---

pyjq/08_summary_for_all_endpoints_get.py

Added license header (issue #83)

---

pyjq/09_summary_for_all_endpoints_delete.py

Added license header (issue #84)

---

pyjq/10_search_endpoint.py

Added license header (issue #85)

---

pyjq/11_has_get_method.py

Added license header (issue #86)

---

pyjq/12_has_delete_method.py

Added license header (issue #87)

---

pyjq/13_get_parameters.py

Added license header (issue #88)

---

pyjq/14_no_text_processing.py

Added license header (issue #89)

---

requests/11_get_binary_data.py

Added license header (issue #139)

Added license header (issue #139)

---

requests/12_binary_data_png_image.py

Added license header (issue #140)

Added license header (issue #140)

---

requests/13_binary_data_jpeg_image.py

Added license header (issue #141)

Added license header (issue #141)

---

requests/14_binary_data_by_header_png.py

Added license header (issue #142)

Added license header (issue #142)

---

requests/15_binary_data_by_header_jpeg.py

Added license header (issue #143)

Added license header (issue #143)

---

requests/16_patch_method.py

Added license header (issue #144)

Added license header (issue #144)

---

requests/17_put_method.py

Added license header (issue #145)

Added license header (issue #145)

---

requests/20_session_cookie.py

Added license header (issue #148)

Added license header (issue #148)

---

requests/19_cookies.py

Added license header (issue #147)

Added license header (issue #147)

---

requests/18_options_method.py

Added license header (issue #146)

Added license header (issue #146)

---

pil/01_basic_usage.py

Added license header (issue #170)

Added license header (issue #170)

---

pil/02_error_handling.py

Added license header (issue #171)

Added license header (issue #171)

---

pil/03_image_info.py

Added license header (issue #172)

Added license header (issue #172)

---

pil/04_save_image.py

Added license header (issue #173)

Added license header (issue #173)

---

pil/05_show_image.py

Added license header (issue #174)

Added license header (issue #174)

---

pil/06_show_thumbnail.py

Added license header (issue #175)

Added license header (issue #175)

---

pil/07_save_thumbnail.py

Added license header (issue #176)

Added license header (issue #176)

---

pil/08_simple_filter.py

Added license header (issue #177)

Added license header (issue #177)

---

pil/09_other_filters.py

Added license header (issue #178)

Added license header (issue #178)

---

pil/10_convert_image_to_grayscale.py

Added license header (issue #179)

Added license header (issue #179)

---

pil/30_image_math.py

Added license header (issue #219)

Added license header (issue #219)

---

pil/27_polyline.py

Added license header (issue #216)

Added license header (issue #216)

---

pil/28_circles.py

Added license header (issue #217)

Added license header (issue #217)

---

pil/29_text.py

Added license header (issue #218)

Added license header (issue #218)

---

pil/25_draw_grid.py

Added license header (issue #214)

Added license header (issue #214)

---

pil/26_colors_rgb.py

Added license header (issue #215)

Added license header (issue #215)

---

pil/23_rgb_palette.py

Added license header (issue #212)

Added license header (issue #212)

---

pil/24_hsl_palette.py

Added license header (issue #213)

Added license header (issue #213)

---

pil/21_bw_image_statistic.py

Added license header (issue #210)

Added license header (issue #210)

---

pil/22_histogram.py

Added license header (issue #211)

Added license header (issue #211)

---

pil/31_image_math_max.py

Added license header (issue #230)

Added license header (issue #230)

---

pil/32_image_math_min.py

Added license header (issue #231)

Added license header (issue #231)

---

pil/33_image_math_add.py

Added license header (issue #232)

Added license header (issue #232)

---

pil/34_image_math_sub.py

Added license header (issue #233)

Added license header (issue #233)

---

pil/35_image_math_mul.py

Added license header (issue #234)

Added license header (issue #234)

---

pil/40_image_math_not.py

Added license header (issue #239)

Added license header (issue #239)

---

pil/36_image_math_avg.py

Added license header (issue #235)

Added license header (issue #235)

---

pil/37_image_math_and.py

Added license header (issue #236)

Added license header (issue #236)

---

pil/38_image_math_or.py

Added license header (issue #237)

Added license header (issue #237)

---

pil/39_image_math_xor.py

Added license header (issue #238)

Added license header (issue #238)

---

pil/41_image_morph_bitmap.py

https://github.com/tisnik/python-programming-courses/commit/7444c6470c435c1954b0ed9a30c5347e802dd98d

Added license header (issue #250)

---

pil/42_image_morph_negate.py

Added license header (issue #251)

Added license header (issue #251)

---

pil/43_image_morph_edges.py

Added license header (issue #252)

Added license header (issue #252)

---

pil/44_image_morph_inner_edges.py

Added license header (issue #253)

Added license header (issue #253)

---

pil/45_image_morph_dilate_4.py

Added license header (issue #254)

Added license header (issue #254)

---

pil/46_image_morph_dilate_8.py

Added license header (issue #255)

Added license header (issue #255)

---

pil/47_image_morph_erosion_4.py

Added license header (issue #256)

Added license header (issue #256)

---

pil/48_image_morph_erosion_8.py

Added license header (issue #257)

Added license header (issue #257)

---

pil/draw_house_one_line_drawing.py

Added license header (issue #258)

Added license header (issue #258)

---

pillow/11_convert_image_to_black_white.py

Added license header (issue #434)

Added license header (issue #434)

---

pillow/12_image_ops_autocontrast.py

Added license header (issue #433)

Added license header (issue #433)

---

pillow/13_image_ops_autocontrast_cutoff.py

Added license header (issue #435)

Added license header (issue #435)

---

pillow/14_image_ops_posterize.py

Added license header (issue #436)

Added license header (issue #436)

---

pillow/15_image_ops_posterize_grayscale.py

Added license header (issue #437)

Added license header (issue #437)

---

pillow/16_image_enhance_sharpness.py

Added license header (issue #438)

Added license header (issue #438)

---

pillow/17_image_enhance_contrast.py

Added license header (issue #439)

Added license header (issue #439)

---

pillow/18_image_enhance_brightness.py

Added license header (issue #440)

Added license header (issue #440)

---

pillow/19_image_enhance_color.py

Added license header (issue #441)

Added license header (issue #441)

---

pillow/20_image_statistic.py

Added license header (issue #442)

Added license header (issue #442)

---

pillow/30_image_math.py

Added license header (issue #452)

Added license header (issue #452)

---

pillow/29_text.py

Added license header (issue #451)

Added license header (issue #451)

---

pillow/28_circles.py

Added license header (issue #450)

Added license header (issue #450)

---

pillow/27_polyline.py

Added license header (issue #449)

Added license header (issue #449)

---

pillow/26_colors_rgb.py

Added license header (issue #448)

Added license header (issue #448)

---

pillow/25_draw_grid.py

Added license header (issue #447)

Added license header (issue #447)

---

pillow/24_hsl_palette.py

Added license header (issue #446)

Added license header (issue #446)

---

pillow/23_rgb_palette.py

Added license header (issue #445)

Added license header (issue #445)

---

pillow/22_histogram.py

Added license header (issue #444)

Added license header (issue #444)

---

pillow/21_bw_image_statistic.py

Added license header (issue #443)

Added license header (issue #443)

---

pillow/31_image_math_max.py

Added license header (issue #453)

Added license header (issue #453)

---

pillow/32_image_math_min.py

Added license header (issue #454)

Added license header (issue #454)

---

pillow/33_image_math_add.py

Added license header (issue #455)

Added license header (issue #455)

---

pillow/34_image_math_sub.py

Added license header (issue #456)

Added license header (issue #456)

---

pillow/40_image_math_not.py

Added license header (issue #462)

Added license header (issue #462)

---

pillow/35_image_math_mul.py

Added license header (issue #457)

Added license header (issue #457)

---

pillow/36_image_math_avg.py

Added license header (issue #458)

Added license header (issue #458)

---

pillow/37_image_math_and.py

Added license header (issue #459)

Added license header (issue #459)

---

pillow/38_image_math_or.py

Added license header (issue #460)

Added license header (issue #460)

---

pillow/39_image_math_xor.py

Added license header (issue #461)

Added license header (issue #461)

---

pillow/41_image_morph_bitmap.py

Added license header (issue #463)

Added license header (issue #463)

---

pillow/42_image_morph_negate.py

Added license header (issue #464)

Added license header (issue #464)

---

pillow/43_image_morph_edges.py

Added license header (issue #465)

Added license header (issue #465)

---

pillow/44_image_morph_inner_edges.py

Added license header (issue #466)

Added license header (issue #466)
